### ISSUE TITLE
Problem with UseInternalServerErrorOnException/InternalServerErrorOnExceptionMiddleware

### ISSUE THREAD

**Issue by RLaptev** [ASP-NET-MVC-Boilerplate/Framework#7]
On the production site that uses this Boilerplate I temporary turned stdout logging, and I see random errors like the one below. Looks like InternalServerErrorOnExceptionMiddleware is being called, but it's failing because the response code is already set. Is there a workaround for this issue?  I can't even figure out what is causing this random 500 error.... 

Thanks.

info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action PSA_Public_Site.Controllers.ps.Get (PSA_Public_Site) in 127.0757ms
info: Boilerplate.AspNetCore.Middleware.InternalServerErrorOnExceptionMiddleware[0]
      Executing InternalServerErrorOnExceptionMiddleware, setting HTTP status code 500.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      **Connection id "0HL0ITDU5M447": An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set, response has already started.**
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Boilerplate.AspNetCore.Middleware.InternalServerErrorOnExceptionMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by RLaptev** [comment]
I solved the above problem by implementing my own version of `InternalServerErrorOnExceptionMiddleware`  that only sets `context.Response.StatusCode = StatusCodes.Status500InternalServerError;` when `context.Response.HasStarted` is false.
